# =========================
# DEVELOPMENT
# =========================
FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=development

RUN corepack enable

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
